### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by Amoryan** [minimAluminiumalism/AfreecaTVCrawler#2]
Traceback (most recent call last):
  File "Afreeca_Crawler.py", line 199, in <module>
    AfreecaSpider().run()
  File "Afreeca_Crawler.py", line 156, in run
    video_info_url = self.get_video_info_url()
  File "Afreeca_Crawler.py", line 39, in get_video_info_url
    response = requests.get(self.base_url, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)

**Comment by Amoryan** [comment]
我使用readme的步骤，然后下载readme上的视频，报错
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by Amoryan** [comment]
需要帮助，谢谢

**Comment by minimAluminiumalism** [comment]
我在服务器上测试中并未遇到此问题，由于个人近期所处环境网络状况较差，无法在本机上进行完整的测试。你可以按以下思路解决：

1. 这应该是一个与 requests 包有关的错误，请参考[此链接](https://www.jianshu.com/p/f8e82dddad0b)，或自行 Google 寻找教程重装你的 requests；
2. 更换网络环境或一台机器，看问题是否复现。

如问题依然存在，请提供详细信息，包括平台和运营商（VPS 服务商）
